name: Renew Lagarde Dev Org Lease
run-name: ${{ github.actor }} triggered dev org renewal build
#on: [push]
on:
  schedule:
    - cron:  '30 20 * * TUE'
  workflow_dispatch:

permissions:
  contents: read


jobs:
  dev-org-renew:
    runs-on: ubuntu-latest
    environment: LagardeAFDevOrgRenew
    steps:
      - uses: actions/checkout@v4
        with: 
          ref: main
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: 'Install CLI'
        run: npm install @salesforce/cli --location=global
      - run: sf --version
      - name: 'Authenticate to Agentforce org'
        run: |
            echo ${{ secrets.LAGARDE_AF_DEV_ORG_URL }} > ./LAGARDE_AF_DEV_ORG_URL.txt
            ls -al ./LAGARDE_AF_DEV_ORG_URL.txt
            sf org login sfdx-url -f ./LAGARDE_AF_DEV_ORG_URL.txt -a LagardeAFDevOrgRenew -d
      - name: 'Query data'
        run: |
            sf data query --query "select name from organization" -o LagardeAFDevOrgRenew
